T_INDICATIF_PRESENT = 'indicatif présent'
T_INDICATIF_IMPARFAIT = 'indicatif imparfait'
T_INDICATIF_FUTUR_SIMPLE = 'indicatif futur simple'
T_INDICATIF_PASSE_SIMPLE = 'indicatif passé simple'
T_SUBJONCTIF_PRESENT = 'subjonctif présent'
T_SUBJONCTIF_IMPARFAIT = 'subjonctif imparfait'
T_CONDITIONNEL_PRESENT = 'conditionnel présent'
T_IMPERATIF_PRESENT = 'impératif présent'
T_PARTICIPE_PRESENT = 'participe présent'
T_PARTICIPE_PASSE = 'participe passé'

TIMECODES = [
    T_INDICATIF_PRESENT,
    T_INDICATIF_IMPARFAIT,
    T_INDICATIF_FUTUR_SIMPLE,
    T_INDICATIF_PASSE_SIMPLE,
    T_SUBJONCTIF_PRESENT,
    T_SUBJONCTIF_IMPARFAIT,
    T_CONDITIONNEL_PRESENT,
    T_IMPERATIF_PRESENT,
    T_PARTICIPE_PRESENT,
    T_PARTICIPE_PASSE
]

ENTITIES = ['1S', '2S', '3S', '1P', '2P', '3P']
ENTITIES_M = ['1SM', '2SM', '3SM', '1PM', '2PM', '3PM']
ENTITIES_F = ['1SF', '2SF', '3SF', '1PF', '2PF', '3PF']

E1S, E2S, E3S, E1P, E2P, E3P = ENTITIES
E1SM, E2SM, E3SM, E1PM, E2PM, E3PM = ENTITIES_M
E1SF, E2SF, E3SF, E1PF, E2PF, E3PF = ENTITIES_F

ENTITYCODES = ENTITIES + ENTITIES_M + ENTITIES_F
